import React, {useState} from 'react';
import { apiFetch } from '../api';

const steps = ['Business Information','Location Information','Upload Inventory / Count Sheet','Review Imported Items','Categories','Storage Areas','Units of Measure','Initial Users','Review & Finish'];
export const BusinessStartView: React.FC = () => {
  const [step,setStep]=useState(0), [file,setFile]=useState<File|null>(null), [preview,setPreview]=useState<any>(null), [busy,setBusy]=useState(false), [notice,setNotice]=useState('');
  const readResponse=async(r:Response)=>{const text=await r.text();try{return JSON.parse(text)}catch{return {detail:r.ok?'The server returned an unreadable response. Please refresh and try again.':`Upload failed (${r.status}).`}}};
  const upload=async()=>{ if(!file)return; setBusy(true); const form=new FormData();form.append('file',file);try{const r=await apiFetch('/api/business-start/imports',{method:'POST',body:form});const d=await readResponse(r);if(r.ok){setPreview(d);setStep(3)}else setNotice(d.detail||'Upload failed');}catch{setNotice('Could not reach the server. Please try again.')}finally{setBusy(false)} };
  const finish=async()=>{if(!preview)return;setBusy(true);try{const r=await apiFetch(`/api/business-start/imports/${preview.id}/finish`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rows:preview.rows})});const d=await readResponse(r);setNotice(r.ok?`Imported ${d.created} items and generated a count sheet.`:d.detail||'Import failed');if(r.ok)setStep(8)}catch{setNotice('Could not reach the server. Please try again.')}finally{setBusy(false)}};
  const updateRow=(i:number,key:string,value:any)=>setPreview({...preview,rows:preview.rows.map((r:any,n:number)=>n===i?{...r,[key]:value}:r)});
  return <div className="space-y-6 max-w-6xl"><div><h2 className="text-2xl font-bold">Business Start</h2><p className="text-zinc-400">Set up a restaurant location and turn its existing count sheet into the central Item Master.</p></div><div className="flex gap-2 overflow-x-auto pb-2">{steps.map((s,i)=><button key={s} onClick={()=>i<=step&&setStep(i)} className={`shrink-0 text-xs px-3 py-2 rounded-full ${i===step?'bg-emerald-600 text-white':i<step?'bg-zinc-700 text-zinc-200':'bg-zinc-900 text-zinc-500'}`}>{i+1}. {s}</button>)}</div>{notice&&<div className="bg-emerald-950 border border-emerald-800 text-emerald-200 p-3 rounded">{notice}</div>}
  {step===0&&<SetupCard title="Business Information" text="Your organization is already connected. You can update formal business details in Administration." next={()=>setStep(1)}/>} {step===1&&<SetupCard title="Location Information" text="Choose the active location in the top bar. Business Start will build its count sheet for that location." next={()=>setStep(2)}/>} {step===2&&<div className="bg-zinc-900 border border-zinc-700 rounded-xl p-6 space-y-4"><h3 className="font-bold">Upload inventory or count sheet</h3><p className="text-sm text-zinc-400">CSV and Excel preserve columns best. PDF text is extracted for review; no records are created yet.</p><input type="file" accept=".csv,.xlsx,.xls,.pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/><button disabled={!file||busy} onClick={upload} className="bg-emerald-700 disabled:opacity-50 px-4 py-2 rounded">{busy?'Reading sheet…':'Create import preview'}</button></div>}
  {step===3&&preview&&<div className="space-y-4"><div className="bg-zinc-900 border border-zinc-700 rounded-xl p-4"><h3 className="font-bold">Map columns</h3><p className="text-sm text-zinc-400">Review the detected mapping before importing. You can edit every row below.</p><div className="grid grid-cols-2 md:grid-cols-4 gap-2 mt-3 text-xs">{Object.entries(preview.mapping).filter(([,v])=>v).map(([k,v])=><div key={k} className="bg-zinc-800 p-2 rounded"><span className="text-zinc-500">{String(v)}</span><br/>→ {k.replace('_',' ')}</div>)}</div></div><div className="bg-zinc-900 border border-zinc-700 rounded-xl overflow-x-auto"><table className="w-full text-xs"><thead className="text-zinc-400"><tr><th className="p-3">Import?</th><th>Item Name</th><th>Category</th><th>Storage Area</th><th>Count Unit</th><th>Purchase Unit</th><th>Cost</th><th>Status</th></tr></thead><tbody>{preview.rows.map((r:any,i:number)=><tr key={i} className="border-t border-zinc-800"><td className="p-2 text-center"><input type="checkbox" checked={r.selected} onChange={e=>updateRow(i,'selected',e.target.checked)}/></td>{['item_name','category','storage_location','count_uom','purchase_uom','current_cost'].map(k=><td key={k} className="p-1"><input value={r[k]||''} onChange={e=>updateRow(i,k,e.target.value)} className="w-full bg-zinc-800 p-2 rounded"/></td>)}<td className={r.status==='Ready'?'text-emerald-400':'text-amber-400'}>{r.status}</td></tr>)}</tbody></table></div><button disabled={busy} onClick={finish} className="bg-emerald-700 px-4 py-2 rounded">{busy?'Importing…':'Finish import & create count sheet'}</button></div>}
  {step>=4&&step<8&&<SetupCard title={steps[step]} text="This reusable catalog setting is ready to manage from Items. Add custom values as needed; nothing is hard-coded." next={()=>setStep(step+1)}/>} {step===8&&<SetupCard title="Business Start complete" text="Your item master is now the shared source for counts, invoices, vendor mappings, recipes, waste, transfers, purchasing, and cost reporting." next={()=>setStep(0)} action="Start another import"/>}</div>
}
const SetupCard=({title,text,next,action='Continue'}:{title:string,text:string,next:()=>void,action?:string})=><div className="bg-zinc-900 border border-zinc-700 rounded-xl p-6 space-y-4"><h3 className="font-bold text-lg">{title}</h3><p className="text-zinc-400">{text}</p><button onClick={next} className="bg-emerald-700 px-4 py-2 rounded">{action}</button></div>;
